# Generated by Django 2.2.5 on 2019-10-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_populate_cors_allowed_origins'),
        ('users', '0021_add_require_registered_client_field'),
    ]

    operations = [
    ]
