# Generated by Django 2.2.6 on 2019-11-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontenttranslation',
            name='privacy_policy_link_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='privacy policy link name'),
        ),
    ]
